"""add unique constraint to team_member_clients

Revision ID: 92e857064d35
Revises: 338cb167886a
Create Date: 2026-04-21 22:10:52.026891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e857064d35'
down_revision = '338cb167886a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member_clients', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tmc_member_client', ['team_member_id', 'client_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member_clients', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tmc_member_client', type_='unique')

    # ### end Alembic commands ###
