"""add ad level columns

Revision ID: d0620082110b
Revises: 92e857064d35
Create Date: 2026-04-23 23:00:35.039300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0620082110b'
down_revision = '92e857064d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ad_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_metrics', schema=None) as batch_op:
        batch_op.drop_column('ad_name')
        batch_op.drop_column('ad_id')

    # ### end Alembic commands ###
